export const powerlifting2024 = [
  {
    "": "",
    __1: "",
    __2: "",
    __3: "",
    "BJELOVAR POWERLIFTING": "",
    __4: "",
    __5: "",
    __6: "",
  },
  {
    "": "",
    __1: "ŽENE",
    __2: "",
    __3: "",
    "BJELOVAR POWERLIFTING": "",
    __4: "",
    __5: "",
    __6: "",
  },
  {
    "": "",
    __1: "SUB-JUNIOR",
    __2: "",
    __3: "",
    "BJELOVAR POWERLIFTING": "",
    __4: "",
    __5: "",
    __6: "",
  },
  {
    "": "",
    __1: 52,
    __2: "",
    __3: "",
    "BJELOVAR POWERLIFTING": "",
    __4: "",
    __5: "",
    __6: "",
  },
  {
    "": 1,
    __1: "",
    __2: 1,
    __3: "ANAMARIJA",
    "BJELOVAR POWERLIFTING": "MAMIĆ",
    __4: 2009,
    __5: "REBEL WARRIOR",
    __6: 237,
  },
  {
    "": 2,
    __1: "",
    __2: 2,
    __3: "TARA",
    "BJELOVAR POWERLIFTING": "PETROVIĆ",
    __4: 2006,
    __5: "GUMENI MEDVJEDIĆI",
    __6: 213,
  },
  {
    "": "",
    __1: 57,
    __2: "",
    __3: "",
    "BJELOVAR POWERLIFTING": "",
    __4: "",
    __5: "",
    __6: "",
  },
  {
    "": 3,
    __1: "",
    __2: 1,
    __3: "LARA",
    "BJELOVAR POWERLIFTING": "ŽIC",
    __4: 2006,
    __5: "TAZ",
    __6: 278.5,
  },
  {
    "": 4,
    __1: "",
    __2: 2,
    __3: "HANA",
    "BJELOVAR POWERLIFTING": "ŽUPANOVIĆ",
    __4: 2006,
    __5: "KRATOS",
    __6: 253.5,
  },
  {
    "": "",
    __1: 69,
    __2: "",
    __3: "",
    "BJELOVAR POWERLIFTING": "",
    __4: "",
    __5: "",
    __6: "",
  },
  {
    "": 5,
    __1: "",
    __2: 1,
    __3: "NIKOLINA",
    "BJELOVAR POWERLIFTING": "KALAICA",
    __4: 2006,
    __5: "DEPTH DOMINATORS",
    __6: "X",
  },
  {
    "": 6,
    __1: "",
    __2: 2,
    __3: "DORA",
    "BJELOVAR POWERLIFTING": "FAŽON",
    __4: 2007,
    __5: "POZOJ",
    __6: "X",
  },
  {
    "": "",
    __1: "84+",
    __2: "",
    __3: "",
    "BJELOVAR POWERLIFTING": "",
    __4: "",
    __5: "",
    __6: "",
  },
  {
    "": 7,
    __1: "",
    __2: 1,
    __3: "MAGDALENA",
    "BJELOVAR POWERLIFTING": "FARINA",
    __4: 2006,
    __5: "BODY ART",
    __6: 347.5,
  },
  {
    "": 8,
    __1: "",
    __2: 2,
    __3: "EMA",
    "BJELOVAR POWERLIFTING": "ILIĆ",
    __4: 2007,
    __5: "TAZ",
    __6: 310,
  },
  {
    "": "",
    __1: "JUNIOR",
    __2: "",
    __3: "",
    "BJELOVAR POWERLIFTING": "",
    __4: "",
    __5: "",
    __6: "",
  },
  {
    "": "",
    __1: 57,
    __2: "",
    __3: "",
    "BJELOVAR POWERLIFTING": "",
    __4: "",
    __5: "",
    __6: "",
  },
  {
    "": 9,
    __1: "",
    __2: 1,
    __3: "MATEA",
    "BJELOVAR POWERLIFTING": "KUCLJAK",
    __4: 2003,
    __5: "NABILDANI MOZAK",
    __6: "X",
  },
  {
    "": "",
    __1: 63,
    __2: "",
    __3: "",
    "BJELOVAR POWERLIFTING": "",
    __4: "",
    __5: "",
    __6: "",
  },
  {
    "": 10,
    __1: "",
    __2: 1,
    __3: "KEONA CHIARA",
    "BJELOVAR POWERLIFTING": "ČASNI",
    __4: 2005,
    __5: "POZOJ",
    __6: "X",
  },
  {
    "": "",
    __1: 69,
    __2: "",
    __3: "",
    "BJELOVAR POWERLIFTING": "",
    __4: "",
    __5: "",
    __6: "",
  },
  {
    "": 11,
    __1: "",
    __2: 1,
    __3: "ANA",
    "BJELOVAR POWERLIFTING": "JOZINOVIĆ",
    __4: "2005.",
    __5: "ŠTANGA",
    __6: 325,
  },
  {
    "": 12,
    __1: "",
    __2: 2,
    __3: "LAURA",
    "BJELOVAR POWERLIFTING": "VULIĆ",
    __4: "2003.",
    __5: "GUMENI MEDVJEDIĆI",
    __6: 323,
  },
  {
    "": 13,
    __1: "",
    __2: 3,
    __3: "MARČELINA",
    "BJELOVAR POWERLIFTING": "FILIPOVIĆ",
    __4: "2005.",
    __5: "DEPTH DOMINATORS",
    __6: 290,
  },
  {
    "": "",
    __1: 76,
    __2: "",
    __3: "",
    "BJELOVAR POWERLIFTING": "",
    __4: "",
    __5: "",
    __6: "",
  },
  {
    "": 14,
    __1: "",
    __2: 1,
    __3: "VITA",
    "BJELOVAR POWERLIFTING": "GRGIĆ",
    __4: "2003.",
    __5: "GUMENI MEDVJEDIĆI",
    __6: 315,
  },
  {
    "": 15,
    __1: "",
    __2: 2,
    __3: "EMINA",
    "BJELOVAR POWERLIFTING": "KONDIĆ",
    __4: "2005.",
    __5: "ADAMAS",
    __6: 305,
  },
  {
    "": 16,
    __1: "",
    __2: 3,
    __3: "HANA",
    "BJELOVAR POWERLIFTING": "VRESK",
    __4: "2001.",
    __5: "BJELOWBAR",
    __6: 270,
  },
  {
    "": 17,
    __1: "",
    __2: 4,
    __3: "ANTEA",
    "BJELOVAR POWERLIFTING": "VOLAREVIĆ",
    __4: "2005.",
    __5: "NABILDANI MOZAK",
    __6: "X",
  },
  {
    "": 18,
    __1: "",
    __2: 5,
    __3: "EMILI",
    "BJELOVAR POWERLIFTING": "LIPOŠĆAK",
    __4: "2002.",
    __5: "ŠTANGA",
    __6: "X",
  },
  {
    "": "",
    __1: 84,
    __2: "",
    __3: "",
    "BJELOVAR POWERLIFTING": "",
    __4: "",
    __5: "",
    __6: "",
  },
  {
    "": 19,
    __1: "",
    __2: 1,
    __3: "VALENTINA",
    "BJELOVAR POWERLIFTING": "VELIĆ",
    __4: "2005.",
    __5: "VIROVITICA",
    __6: 327.5,
  },
  {
    "": "",
    __1: "OPEN",
    __2: "",
    __3: "",
    "BJELOVAR POWERLIFTING": "",
    __4: "",
    __5: "",
    __6: "",
  },
  {
    "": "",
    __1: 47,
    __2: "",
    __3: "",
    "BJELOVAR POWERLIFTING": "",
    __4: "",
    __5: "",
    __6: "",
  },
  {
    "": 20,
    __1: "",
    __2: 1,
    __3: "IRA",
    "BJELOVAR POWERLIFTING": "TASIĆ",
    __4: 1997,
    __5: "GUMENI MEDVJEDIĆI",
    __6: "X",
  },
  {
    "": "",
    __1: 57,
    __2: "",
    __3: "",
    "BJELOVAR POWERLIFTING": "",
    __4: "",
    __5: "",
    __6: "",
  },
  {
    "": 21,
    __1: "",
    __2: 1,
    __3: "TEUTA",
    "BJELOVAR POWERLIFTING": "JAKUPOVIĆ",
    __4: 1988,
    __5: "GUMENI MEDVJEDIĆI",
    __6: 407.5,
  },
  {
    "": 22,
    __1: "",
    __2: 2,
    __3: "MELISA",
    "BJELOVAR POWERLIFTING": "MATULIN",
    __4: 2005,
    __5: "POZOJ",
    __6: 301,
  },
  {
    "": 23,
    __1: "",
    __2: 3,
    __3: "DORA",
    "BJELOVAR POWERLIFTING": "RINČIĆ",
    __4: 2001,
    __5: "SAMO MIŠIĆI",
    __6: 300,
  },
  {
    "": 24,
    __1: "",
    __2: 4,
    __3: "KLARA",
    "BJELOVAR POWERLIFTING": "MENDAŠ",
    __4: 2000,
    __5: "BJELOWBAR",
    __6: 282.5,
  },
  {
    "": 25,
    __1: "",
    __2: 5,
    __3: "MIRNA",
    "BJELOVAR POWERLIFTING": "MARTINČIĆ",
    __4: 1996,
    __5: "SAMO MIŠIĆI",
    __6: 277.5,
  },
  {
    "": 26,
    __1: "",
    __2: 6,
    __3: "ANITA",
    "BJELOVAR POWERLIFTING": "HAJNIĆ",
    __4: 1992,
    __5: "TAZ",
    __6: 265,
  },
  {
    "": 27,
    __1: "",
    __2: 7,
    __3: "VICTORIA MARGIORY",
    "BJELOVAR POWERLIFTING": "OTRILLA AGAMA",
    __4: 1994,
    __5: "BJELOWBAR",
    __6: "X",
  },
  {
    "": 28,
    __1: "",
    __2: 8,
    __3: "BARBARA",
    "BJELOVAR POWERLIFTING": "URŠANIĆ",
    __4: 1992,
    __5: "NABILDANI MOZAK",
    __6: "X",
  },
  {
    "": 29,
    __1: "",
    __2: 9,
    __3: "ANTONELA",
    "BJELOVAR POWERLIFTING": "MEHMET",
    __4: 2003,
    __5: "OSIJEK 031",
    __6: "X",
  },
  {
    "": "",
    __1: 63,
    __2: "",
    __3: "",
    "BJELOVAR POWERLIFTING": "",
    __4: "",
    __5: "",
    __6: "",
  },
  {
    "": 30,
    __1: "",
    __2: 1,
    __3: "SUZANA",
    "BJELOVAR POWERLIFTING": "GAŠPAROVIĆ",
    __4: 1987,
    __5: "TAZ",
    __6: 305,
  },
  {
    "": 31,
    __1: "",
    __2: 2,
    __3: "ENIA",
    "BJELOVAR POWERLIFTING": "MAJETIĆ",
    __4: 1996,
    __5: "VIROVITICA",
    __6: 265,
  },
  {
    "": 32,
    __1: "",
    __2: 3,
    __3: "LUKRECIJA",
    "BJELOVAR POWERLIFTING": "BABIĆ",
    __4: 2001,
    __5: "BJELOWBAR",
    __6: 255,
  },
  {
    "": "",
    __1: 69,
    __2: "",
    __3: "",
    "BJELOVAR POWERLIFTING": "",
    __4: "",
    __5: "",
    __6: "",
  },
  {
    "": 33,
    __1: "",
    __2: 1,
    __3: "MATEA",
    "BJELOVAR POWERLIFTING": "BUMBA",
    __4: "1999.",
    __5: "VIROVITICA",
    __6: 420,
  },
  {
    "": 34,
    __1: "",
    __2: 2,
    __3: "MELANIJA",
    "BJELOVAR POWERLIFTING": "POMPER",
    __4: 1995,
    __5: "GUMENI MEDVJEDIĆI",
    __6: 325,
  },
  {
    "": 35,
    __1: "",
    __2: 3,
    __3: "NIKOLINA",
    "BJELOVAR POWERLIFTING": "JOSIPOVIĆ",
    __4: 1996,
    __5: "TAZ",
    __6: "X",
  },
  {
    "": "",
    __1: 76,
    __2: "",
    __3: "",
    "BJELOVAR POWERLIFTING": "",
    __4: "",
    __5: "",
    __6: "",
  },
  {
    "": 36,
    __1: "",
    __2: 1,
    __3: "MARIA MAGDALENA",
    "BJELOVAR POWERLIFTING": "GORIČANEC",
    __4: "2004.",
    __5: "POZOJ",
    __6: 380,
  },
  {
    "": "",
    __1: 84,
    __2: "",
    __3: "",
    "BJELOVAR POWERLIFTING": "",
    __4: "",
    __5: "",
    __6: "",
  },
  {
    "": 37,
    __1: "",
    __2: 1,
    __3: "MARINELA",
    "BJELOVAR POWERLIFTING": "FRAS",
    __4: 1997,
    __5: "GUMENI MEDVJEDIĆI",
    __6: 451,
  },
  {
    "": 38,
    __1: "",
    __2: 2,
    __3: "BARBARA",
    "BJELOVAR POWERLIFTING": "ŠKEVIN",
    __4: 1996,
    __5: "GUMENI MEDVJEDIĆI",
    __6: 315,
  },
  {
    "": 39,
    __1: "",
    __2: 3,
    __3: "MAJA",
    "BJELOVAR POWERLIFTING": "MAŠEK",
    __4: 1993,
    __5: "GUMENI MEDVJEDIĆI",
    __6: 260,
  },
  {
    "": 40,
    __1: "",
    __2: 4,
    __3: "DARIA",
    "BJELOVAR POWERLIFTING": "BUNJA",
    __4: 1997,
    __5: "BJELOWBAR",
    __6: "X",
  },
  {
    "": 41,
    __1: "",
    __2: 5,
    __3: "TARA",
    "BJELOVAR POWERLIFTING": "BAĆE",
    __4: 2002,
    __5: "NABILDANI MOZAK",
    __6: "X",
  },
  {
    "": 42,
    __1: "",
    __2: 6,
    __3: "MARINA",
    "BJELOVAR POWERLIFTING": "KUNAC",
    __4: 1996,
    __5: "REBEL WARRIOR",
    __6: "X",
  },
  {
    "": "",
    __1: "84+",
    __2: "",
    __3: "",
    "BJELOVAR POWERLIFTING": "",
    __4: "",
    __5: "",
    __6: "",
  },
  {
    "": 43,
    __1: "",
    __2: 1,
    __3: "JELENA",
    "BJELOVAR POWERLIFTING": "IVANČIĆ",
    __4: 1993,
    __5: "ŠTANGA",
    __6: 410,
  },
  {
    "": 44,
    __1: "",
    __2: 2,
    __3: "KRISTINA",
    "BJELOVAR POWERLIFTING": "ČOLAK",
    __4: 1994,
    __5: "BJELOWBAR",
    __6: 260,
  },
  {
    "": "",
    __1: "MASTER I",
    __2: "",
    __3: "",
    "BJELOVAR POWERLIFTING": "",
    __4: "",
    __5: "",
    __6: "",
  },
  {
    "": "",
    __1: 52,
    __2: "",
    __3: "",
    "BJELOVAR POWERLIFTING": "",
    __4: "",
    __5: "",
    __6: "",
  },
  {
    "": 45,
    __1: "",
    __2: 1,
    __3: "ALEKSANDRA",
    "BJELOVAR POWERLIFTING": "STJEPANOVIĆ",
    __4: 1983,
    __5: "SAMO MIŠIĆI",
    __6: 260,
  },
  {
    "": "",
    __1: 63,
    __2: "",
    __3: "",
    "BJELOVAR POWERLIFTING": "",
    __4: "",
    __5: "",
    __6: "",
  },
  {
    "": 46,
    __1: "",
    __2: 1,
    __3: "MIRNA",
    "BJELOVAR POWERLIFTING": "RASPOR DORIČIĆ",
    __4: 1982,
    __5: "SAMO MIŠIĆI",
    __6: "X",
  },
  {
    "": "",
    __1: 69,
    __2: "",
    __3: "",
    "BJELOVAR POWERLIFTING": "",
    __4: "",
    __5: "",
    __6: "",
  },
  {
    "": 47,
    __1: "",
    __2: 1,
    __3: "BRANIMIRA",
    "BJELOVAR POWERLIFTING": "NOVŠAK",
    __4: 1982,
    __5: "SAMO MIŠIĆI",
    __6: 325,
  },
  {
    "": "",
    __1: "84+",
    __2: "",
    __3: "",
    "BJELOVAR POWERLIFTING": "",
    __4: "",
    __5: "",
    __6: "",
  },
  {
    "": 48,
    __1: "",
    __2: 1,
    __3: "ANDREA",
    "BJELOVAR POWERLIFTING": "MILANKO",
    __4: 1983,
    __5: "ŠTANGA",
    __6: "X",
  },
  {
    "": "",
    __1: "MASTER II",
    __2: "",
    __3: "",
    "BJELOVAR POWERLIFTING": "",
    __4: "",
    __5: "",
    __6: "",
  },
  {
    "": "",
    __1: 63,
    __2: "",
    __3: "",
    "BJELOVAR POWERLIFTING": "",
    __4: "",
    __5: "",
    __6: "",
  },
  {
    "": 49,
    __1: "",
    __2: 1,
    __3: "RENATA",
    "BJELOVAR POWERLIFTING": "GECAN MILEK",
    __4: 1971,
    __5: "POWER CREW",
    __6: 268,
  },
  {
    "": "",
    __1: "",
    __2: "",
    __3: "",
    "BJELOVAR POWERLIFTING": "",
    __4: "",
    __5: "",
    __6: "",
  },
  {
    "": "",
    __1: "MUŠKI",
    __2: "",
    __3: "",
    "BJELOVAR POWERLIFTING": "",
    __4: "",
    __5: "",
    __6: "",
  },
  {
    "": "",
    __1: "SUB-JUNIOR",
    __2: "",
    __3: "",
    "BJELOVAR POWERLIFTING": "",
    __4: "",
    __5: "",
    __6: "",
  },
  {
    "": "",
    __1: 74,
    __2: "",
    __3: "",
    "BJELOVAR POWERLIFTING": "",
    __4: "",
    __5: "",
    __6: "",
  },
  {
    "": 1,
    __1: "",
    __2: 1,
    __3: "STJEPAN",
    "BJELOVAR POWERLIFTING": "KOVAČ",
    __4: 2006,
    __5: "POZOJ",
    __6: 540,
  },
  {
    "": 2,
    __1: "",
    __2: 2,
    __3: "ANDRIJA",
    "BJELOVAR POWERLIFTING": "ŽELEZNJAK",
    __4: 2006,
    __5: "POZOJ",
    __6: 482.5,
  },
  {
    "": "",
    __1: 83,
    __2: "",
    __3: "",
    "BJELOVAR POWERLIFTING": "",
    __4: "",
    __5: "",
    __6: "",
  },
  {
    "": 3,
    __1: "",
    __2: 1,
    __3: "LUKA",
    "BJELOVAR POWERLIFTING": "BENŠIĆ",
    __4: 2006,
    __5: "BJELOWBAR",
    __6: 545,
  },
  {
    "": 4,
    __1: "",
    __2: 2,
    __3: "PETAR",
    "BJELOVAR POWERLIFTING": "RENDULIĆ",
    __4: 2006,
    __5: "ŠTANGA",
    __6: 525,
  },
  {
    "": 5,
    __1: "",
    __2: 3,
    __3: "LUKAS",
    "BJELOVAR POWERLIFTING": "PRENDIVOJ",
    __4: 2007,
    __5: "TAZ",
    __6: 482.5,
  },
  {
    "": 6,
    __1: "",
    __2: 4,
    __3: "DAVID",
    "BJELOVAR POWERLIFTING": "SMOLJAN",
    __4: 2008,
    __5: "GUMENI MEDVJEDIĆI",
    __6: "X",
  },
  {
    "": 7,
    __1: "",
    __2: 5,
    __3: "PAOLO",
    "BJELOVAR POWERLIFTING": "KEBO MOJTIĆ",
    __4: 2006,
    __5: "DEPTH DOMINATORS",
    __6: "X",
  },
  {
    "": 8,
    __1: "",
    __2: 6,
    __3: "MARKO",
    "BJELOVAR POWERLIFTING": "BUJANEC",
    __4: 2007,
    __5: "NABILDANI MOZAK",
    __6: "X",
  },
  {
    "": "",
    __1: 93,
    __2: "",
    __3: "",
    "BJELOVAR POWERLIFTING": "",
    __4: "",
    __5: "",
    __6: "",
  },
  {
    "": 9,
    __1: "",
    __2: 1,
    __3: "NIKOLA",
    "BJELOVAR POWERLIFTING": "ZGREBEC",
    __4: 2006,
    __5: "POZOJ",
    __6: 602.5,
  },
  {
    "": 10,
    __1: "",
    __2: 2,
    __3: "KARLO",
    "BJELOVAR POWERLIFTING": "JURIĆ",
    __4: 2006,
    __5: "DEPTH DOMINATORS",
    __6: 525,
  },
  {
    "": 11,
    __1: "",
    __2: 3,
    __3: "DOMINIK",
    "BJELOVAR POWERLIFTING": "JURICA",
    __4: 2006,
    __5: "KRATOS",
    __6: 472.5,
  },
  {
    "": 12,
    __1: "",
    __2: 4,
    __3: "AMAR",
    "BJELOVAR POWERLIFTING": "KANTAREVIĆ",
    __4: 2006,
    __5: "TAZ",
    __6: 467.5,
  },
  {
    "": 13,
    __1: "",
    __2: 5,
    __3: "BARTOL",
    "BJELOVAR POWERLIFTING": "BAN",
    __4: 2006,
    __5: "NABILDANI MOZAK",
    __6: "X",
  },
  {
    "": 14,
    __1: "",
    __2: 6,
    __3: "ARIAN",
    "BJELOVAR POWERLIFTING": "VUKELIĆ",
    __4: 2007,
    __5: "OSIJEK 031",
    __6: "X",
  },
  {
    "": 15,
    __1: "",
    __2: 7,
    __3: "DORIAN",
    "BJELOVAR POWERLIFTING": "MUTAK",
    __4: 2007,
    __5: "ŠTANGA",
    __6: "X",
  },
  {
    "": 16,
    __1: "",
    __2: 8,
    __3: "LUKA",
    "BJELOVAR POWERLIFTING": "FILJAK",
    __4: 2008,
    __5: "ULTIMATE",
    __6: "X",
  },
  {
    "": "",
    __1: 105,
    __2: "",
    __3: "",
    "BJELOVAR POWERLIFTING": "",
    __4: "",
    __5: "",
    __6: "",
  },
  {
    "": 17,
    __1: "",
    __2: 1,
    __3: "PAVEL",
    "BJELOVAR POWERLIFTING": "GOLEC",
    __4: 2006,
    __5: "ŠTANGA",
    __6: 552.5,
  },
  {
    "": 18,
    __1: "",
    __2: 2,
    __3: "DAVID",
    "BJELOVAR POWERLIFTING": "STIPČIĆ",
    __4: 2006,
    __5: "ŠTANGA",
    __6: "X",
  },
  {
    "": "",
    __1: "120+",
    __2: "",
    __3: "",
    "BJELOVAR POWERLIFTING": "",
    __4: "",
    __5: "",
    __6: "",
  },
  {
    "": 19,
    __1: "",
    __2: 1,
    __3: "IVAN",
    "BJELOVAR POWERLIFTING": "RISTEVSKI",
    __4: 2007,
    __5: "ŠTANGA",
    __6: "X",
  },
  {
    "": "",
    __1: "JUNIOR",
    __2: "",
    __3: "",
    "BJELOVAR POWERLIFTING": "",
    __4: "",
    __5: "",
    __6: "",
  },
  {
    "": "",
    __1: 66,
    __2: "",
    __3: "",
    "BJELOVAR POWERLIFTING": "",
    __4: "",
    __5: "",
    __6: "",
  },
  {
    "": 20,
    __1: "",
    __2: 1,
    __3: "MARKO",
    "BJELOVAR POWERLIFTING": "FILJAK",
    __4: 2004,
    __5: "ULTIMATE",
    __6: "X",
  },
  {
    "": "",
    __1: 83,
    __2: "",
    __3: "",
    "BJELOVAR POWERLIFTING": "",
    __4: "",
    __5: "",
    __6: "",
  },
  {
    "": 21,
    __1: "",
    __2: 1,
    __3: "GABRIEL",
    "BJELOVAR POWERLIFTING": "FRIŠČIĆ",
    __4: 2003,
    __5: "NABILDANI MOZAK",
    __6: 597.5,
  },
  {
    "": 22,
    __1: "",
    __2: 2,
    __3: "VALENTINO",
    "BJELOVAR POWERLIFTING": "TOMIĆ",
    __4: 2004,
    __5: "NABILDANI MOZAK",
    __6: 580,
  },
  {
    "": 23,
    __1: "",
    __2: 3,
    __3: "VAL ADRIEN",
    "BJELOVAR POWERLIFTING": "DEKLEVA",
    __4: 2004,
    __5: "ŠTANGA",
    __6: 525,
  },
  {
    "": 24,
    __1: "",
    __2: 4,
    __3: "MATEO",
    "BJELOVAR POWERLIFTING": "FIJALA",
    __4: "2003.",
    __5: "VIROVITICA",
    __6: "X",
  },
  {
    "": 25,
    __1: "",
    __2: 5,
    __3: "BORNA",
    "BJELOVAR POWERLIFTING": "KROG",
    __4: "2005.",
    __5: "NABILDANI MOZAK",
    __6: "X",
  },
  {
    "": 26,
    __1: "",
    __2: 6,
    __3: "LUKA",
    "BJELOVAR POWERLIFTING": "KEČKEŠ",
    __4: 2004,
    __5: "OSIJEK 031",
    __6: "X",
  },
  {
    "": 27,
    __1: "",
    __2: 7,
    __3: "NOA",
    "BJELOVAR POWERLIFTING": "MIŠ MEŠIĆ",
    __4: 2003,
    __5: "TAZ",
    __6: "X",
  },
  {
    "": "",
    __1: 93,
    __2: "",
    __3: "",
    "BJELOVAR POWERLIFTING": "",
    __4: "",
    __5: "",
    __6: "",
  },
  {
    "": 28,
    __1: "",
    __2: 1,
    __3: "FRAN",
    "BJELOVAR POWERLIFTING": "BARLOVIĆ",
    __4: 2004,
    __5: "POZOJ",
    __6: 620,
  },
  {
    "": 29,
    __1: "",
    __2: 2,
    __3: "MATIJA",
    "BJELOVAR POWERLIFTING": "KUTNJAK",
    __4: 2004,
    __5: "POZOJ",
    __6: 615,
  },
  {
    "": 30,
    __1: "",
    __2: 3,
    __3: "LEON",
    "BJELOVAR POWERLIFTING": "PISKAČ",
    __4: 2002,
    __5: "POWER CREW",
    __6: 605,
  },
  {
    "": 31,
    __1: "",
    __2: 4,
    __3: "MATEJ",
    "BJELOVAR POWERLIFTING": "KUJAVEC",
    __4: 2001,
    __5: "ŠTANGA",
    __6: 557.5,
  },
  {
    "": 32,
    __1: "",
    __2: 5,
    __3: "MAURO",
    "BJELOVAR POWERLIFTING": "RAJČIĆ",
    __4: 2003,
    __5: "ŠTANGA",
    __6: 540,
  },
  {
    "": 33,
    __1: "",
    __2: 6,
    __3: "LUKA",
    "BJELOVAR POWERLIFTING": "MIKULIĆ",
    __4: 2003,
    __5: "NABILDANI MOZAK",
    __6: 500,
  },
  {
    "": 34,
    __1: "",
    __2: 7,
    __3: "ANTONIO",
    "BJELOVAR POWERLIFTING": "ŠĆULAC",
    __4: 2004,
    __5: "TAZ",
    __6: 492.5,
  },
  {
    "": 35,
    __1: "",
    __2: 8,
    __3: "ANDRIJA",
    "BJELOVAR POWERLIFTING": "ADAMOVIĆ",
    __4: 2004,
    __5: "GUMENI MEDVJEDIĆI",
    __6: "X",
  },
  {
    "": 36,
    __1: "",
    __2: 9,
    __3: "KARLO",
    "BJELOVAR POWERLIFTING": "MEĐUGORAC",
    __4: 2003,
    __5: "GUMENI MEDVJEDIĆI",
    __6: "X",
  },
  {
    "": 37,
    __1: "",
    __2: 10,
    __3: "FRAN",
    "BJELOVAR POWERLIFTING": "CANJUGA",
    __4: 2002,
    __5: "NABILDANI MOZAK",
    __6: "X",
  },
  {
    "": 38,
    __1: "",
    __2: 11,
    __3: "PETAR",
    "BJELOVAR POWERLIFTING": "REBIĆ",
    __4: 2003,
    __5: "OSIJEK 031",
    __6: "X",
  },
  {
    "": 39,
    __1: "",
    __2: 12,
    __3: "JONATAN",
    "BJELOVAR POWERLIFTING": "KALEB",
    __4: 2001,
    __5: "OSIJEK 031",
    __6: "X",
  },
  {
    "": 40,
    __1: "",
    __2: 13,
    __3: "VALENTIN",
    "BJELOVAR POWERLIFTING": "VESELČIĆ",
    __4: 2002,
    __5: "OSIJEK 031",
    __6: "X",
  },
  {
    "": 41,
    __1: "",
    __2: 14,
    __3: "MARKO",
    "BJELOVAR POWERLIFTING": "BRLEK",
    __4: 2001,
    __5: "ŠTANGA",
    __6: "X",
  },
  {
    "": "",
    __1: 105,
    __2: "",
    __3: "",
    "BJELOVAR POWERLIFTING": "",
    __4: "",
    __5: "",
    __6: "",
  },
  {
    "": 42,
    __1: "",
    __2: 1,
    __3: "PAVO",
    "BJELOVAR POWERLIFTING": "ŠVENDA",
    __4: 2005,
    __5: "NABILDANI MOZAK",
    __6: 583,
  },
  {
    "": 43,
    __1: "",
    __2: 2,
    __3: "JAKOV",
    "BJELOVAR POWERLIFTING": "MRŠO",
    __4: 2004,
    __5: "NABILDANI MOZAK",
    __6: 487.5,
  },
  {
    "": 44,
    __1: "",
    __2: 3,
    __3: "RUAS",
    "BJELOVAR POWERLIFTING": "BEIDEGGER",
    __4: 2004,
    __5: "POWER CREW",
    __6: "X",
  },
  {
    "": 45,
    __1: "",
    __2: 4,
    __3: "DINO",
    "BJELOVAR POWERLIFTING": "ODOBAŠIĆ",
    __4: 2004,
    __5: "ŠTANGA",
    __6: "X",
  },
  {
    "": "",
    __1: "120+",
    __2: "",
    __3: "",
    "BJELOVAR POWERLIFTING": "",
    __4: "",
    __5: "",
    __6: "",
  },
  {
    "": 46,
    __1: "",
    __2: 1,
    __3: "BRUNO",
    "BJELOVAR POWERLIFTING": "PERKOVIĆ",
    __4: 2001,
    __5: "ŠTANGA",
    __6: "X",
  },
  {
    "": "",
    __1: "OPEN",
    __2: "",
    __3: "",
    "BJELOVAR POWERLIFTING": "",
    __4: "",
    __5: "",
    __6: "",
  },
  {
    "": "",
    __1: 66,
    __2: "",
    __3: "",
    "BJELOVAR POWERLIFTING": "",
    __4: "",
    __5: "",
    __6: "",
  },
  {
    "": 47,
    __1: "",
    __2: 1,
    __3: "LUKA",
    "BJELOVAR POWERLIFTING": "BABIĆ",
    __4: 2002,
    __5: "NABILDANI MOZAK",
    __6: 463,
  },
  {
    "": 48,
    __1: "",
    __2: 2,
    __3: "EUGEN",
    "BJELOVAR POWERLIFTING": "ČAUŠEVIĆ",
    __4: 2004,
    __5: "ŠTANGA",
    __6: 397.5,
  },
  {
    "": "",
    __1: 74,
    __2: "",
    __3: "",
    "BJELOVAR POWERLIFTING": "",
    __4: "",
    __5: "",
    __6: "",
  },
  {
    "": 49,
    __1: "",
    __2: 1,
    __3: "ALEKSANDAR",
    "BJELOVAR POWERLIFTING": "KOVAČEVIĆ",
    __4: 1995,
    __5: "ŠTANGA",
    __6: 442.5,
  },
  {
    "": 50,
    __1: "",
    __2: 2,
    __3: "ANTONIO",
    "BJELOVAR POWERLIFTING": "MILETIĆ",
    __4: "1995.",
    __5: "VIROVITICA",
    __6: 400,
  },
  {
    "": 51,
    __1: "",
    __2: 3,
    __3: "LUKA",
    "BJELOVAR POWERLIFTING": "LALIĆ",
    __4: "1999.",
    __5: "BJELOWBAR",
    __6: "X",
  },
  {
    "": 52,
    __1: "",
    __2: 4,
    __3: "VID",
    "BJELOVAR POWERLIFTING": "TOMLJENOVIĆ",
    __4: 1999,
    __5: "BJELOWBAR",
    __6: "X",
  },
  {
    "": 53,
    __1: "",
    __2: 5,
    __3: "LEON",
    "BJELOVAR POWERLIFTING": "ŠUŠNJAR",
    __4: 1998,
    __5: "TAZ",
    __6: "X",
  },
  {
    "": 54,
    __1: "",
    __2: 6,
    __3: "NIKOLA",
    "BJELOVAR POWERLIFTING": "PUH",
    __4: 1999,
    __5: "POZOJ",
    __6: "X",
  },
  {
    "": "",
    __1: 83,
    __2: "",
    __3: "",
    "BJELOVAR POWERLIFTING": "",
    __4: "",
    __5: "",
    __6: "",
  },
  {
    "": 55,
    __1: "",
    __2: 1,
    __3: "WALTER",
    "BJELOVAR POWERLIFTING": "SMAJLOVIĆ",
    __4: "2000.",
    __5: "NABILDANI MOZAK",
    __6: 707.5,
  },
  {
    "": 56,
    __1: "",
    __2: 2,
    __3: "MILOŠ",
    "BJELOVAR POWERLIFTING": "MRMOŠ",
    __4: 2000,
    __5: "ADAMAS",
    __6: 580,
  },
  {
    "": 57,
    __1: "",
    __2: 3,
    __3: "PATRIK",
    "BJELOVAR POWERLIFTING": "KUŠEVIĆ",
    __4: 1999,
    __5: "LIFTAONICA",
    __6: 577.5,
  },
  {
    "": 58,
    __1: "",
    __2: 4,
    __3: "MICHEL",
    "BJELOVAR POWERLIFTING": "MARINOVIĆ",
    __4: 1997,
    __5: "OSIJEK 031",
    __6: 565,
  },
  {
    "": 59,
    __1: "",
    __2: 5,
    __3: "GORAN",
    "BJELOVAR POWERLIFTING": "MITRIĆ",
    __4: 1988,
    __5: "ŠTANGA",
    __6: 552.5,
  },
  {
    "": 60,
    __1: "",
    __2: 6,
    __3: "LEO",
    "BJELOVAR POWERLIFTING": "SKROČE",
    __4: 2002,
    __5: "NABILDANI MOZAK",
    __6: 540,
  },
  {
    "": 61,
    __1: "",
    __2: 7,
    __3: "JURAJ",
    "BJELOVAR POWERLIFTING": "GORUPEC",
    __4: 1991,
    __5: "BJELOWBAR",
    __6: 472.5,
  },
  {
    "": 62,
    __1: "",
    __2: 8,
    __3: "LUKA",
    "BJELOVAR POWERLIFTING": "ĆUK",
    __4: 2000,
    __5: "ŠTANGA",
    __6: 470,
  },
  {
    "": 63,
    __1: "",
    __2: 9,
    __3: "LUKA",
    "BJELOVAR POWERLIFTING": "VOLAREVIĆ",
    __4: 2004,
    __5: "NABILDANI MOZAK",
    __6: 400,
  },
  {
    "": 64,
    __1: "",
    __2: 10,
    __3: "PETAR",
    "BJELOVAR POWERLIFTING": "PERIŠIĆ",
    __4: 1999,
    __5: "DEPTH DOMINATORS",
    __6: "X",
  },
  {
    "": "",
    __1: 93,
    __2: "",
    __3: "",
    "BJELOVAR POWERLIFTING": "",
    __4: "",
    __5: "",
    __6: "",
  },
  {
    "": 65,
    __1: "",
    __2: 1,
    __3: "VALENTINO",
    "BJELOVAR POWERLIFTING": "MARAŠ",
    __4: 1997,
    __5: "LIFTAONICA",
    __6: 712.5,
  },
  {
    "": 66,
    __1: "",
    __2: 2,
    __3: "LEONARDO",
    "BJELOVAR POWERLIFTING": "BLAŽEKOVIĆ",
    __4: 1999,
    __5: "GUMENI MEDVJEDIĆI",
    __6: 735,
  },
  {
    "": 67,
    __1: "",
    __2: 3,
    __3: "KRUNOSLAV",
    "BJELOVAR POWERLIFTING": "DROPUČIĆ",
    __4: 1988,
    __5: "ŠTANGA",
    __6: 642.5,
  },
  {
    "": 68,
    __1: "",
    __2: 4,
    __3: "LUKA",
    "BJELOVAR POWERLIFTING": "TURKOVIĆ",
    __4: 2000,
    __5: "ŠTANGA",
    __6: 600,
  },
  {
    "": 69,
    __1: "",
    __2: 5,
    __3: "RINO",
    "BJELOVAR POWERLIFTING": "ŽUPA",
    __4: 2000,
    __5: "NABILDANI MOZAK",
    __6: 595,
  },
  {
    "": 70,
    __1: "",
    __2: 6,
    __3: "MATEO",
    "BJELOVAR POWERLIFTING": "TOMAŠEVIĆ",
    __4: 1997,
    __5: "ŠTANGA",
    __6: 545,
  },
  {
    "": 71,
    __1: "",
    __2: 7,
    __3: "ROBIN",
    "BJELOVAR POWERLIFTING": "KOVAČIĆ",
    __4: 2004,
    __5: "NABILDANI MOZAK",
    __6: 497.5,
  },
  {
    "": 72,
    __1: "",
    __2: 8,
    __3: "NEMANJA",
    "BJELOVAR POWERLIFTING": "ŽIVANOVIĆ",
    __4: 1999,
    __5: "ADAMAS",
    __6: "X",
  },
  {
    "": 73,
    __1: "",
    __2: 9,
    __3: "DARKO",
    "BJELOVAR POWERLIFTING": "JELENIĆ",
    __4: 1991,
    __5: "ADAMAS",
    __6: "X",
  },
  {
    "": 74,
    __1: "",
    __2: 10,
    __3: "DARKO",
    "BJELOVAR POWERLIFTING": "ŠILIĆ",
    __4: 1997,
    __5: "GUMENI MEDVJEDIĆI",
    __6: "X",
  },
  {
    "": 75,
    __1: "",
    __2: 11,
    __3: "SANEL",
    "BJELOVAR POWERLIFTING": "DEMARK",
    __4: 1996,
    __5: "TAZ",
    __6: "X",
  },
  {
    "": 76,
    __1: "",
    __2: 12,
    __3: "FILIP",
    "BJELOVAR POWERLIFTING": "KUNIĆ",
    __4: 1999,
    __5: "ULTIMATE",
    __6: "X",
  },
  {
    "": 77,
    __1: "",
    __2: 13,
    __3: "BORNA",
    "BJELOVAR POWERLIFTING": "KRALJEVIĆ",
    __4: 1996,
    __5: "OSIJEK 031",
    __6: "X",
  },
  {
    "": "",
    __1: 105,
    __2: "",
    __3: "",
    "BJELOVAR POWERLIFTING": "",
    __4: "",
    __5: "",
    __6: "",
  },
  {
    "": 78,
    __1: "",
    __2: 1,
    __3: "GORDAN",
    "BJELOVAR POWERLIFTING": "KLASIĆ",
    __4: 1996,
    __5: "BJELOWBAR",
    __6: 787.5,
  },
  {
    "": 79,
    __1: "",
    __2: 2,
    __3: "MARIN",
    "BJELOVAR POWERLIFTING": "MILIKIĆ",
    __4: 1998,
    __5: "ŠTANGA",
    __6: 650,
  },
  {
    "": 80,
    __1: "",
    __2: 3,
    __3: "MARTIN",
    "BJELOVAR POWERLIFTING": "CVETKOVIĆ",
    __4: 2000,
    __5: "ŠTANGA",
    __6: 642.5,
  },
  {
    "": 81,
    __1: "",
    __2: 4,
    __3: "LUKA",
    "BJELOVAR POWERLIFTING": "ŽEGURA",
    __4: 2000,
    __5: "NABILDANI MOZAK",
    __6: 625,
  },
  {
    "": 82,
    __1: "",
    __2: 5,
    __3: "JOSIP",
    "BJELOVAR POWERLIFTING": "TORIĆ",
    __4: 1997,
    __5: "NABILDANI MOZAK",
    __6: 622.5,
  },
  {
    "": 83,
    __1: "",
    __2: 6,
    __3: "BERANIMIR",
    "BJELOVAR POWERLIFTING": "BABIĆ",
    __4: 1986,
    __5: "GUMENI MEDVJEDIĆI",
    __6: 577.5,
  },
  {
    "": 84,
    __1: "",
    __2: 7,
    __3: "NIKO",
    "BJELOVAR POWERLIFTING": "FILIPOVIĆ",
    __4: 1996,
    __5: "ADAMAS",
    __6: 517.5,
  },
  {
    "": 85,
    __1: "",
    __2: 8,
    __3: "STAŠA",
    "BJELOVAR POWERLIFTING": "PREMEC",
    __4: 1998,
    __5: "BJELOWBAR",
    __6: "X",
  },
  {
    "": 86,
    __1: "",
    __2: 9,
    __3: "DANIEL",
    "BJELOVAR POWERLIFTING": "DRAGOJEVIĆ",
    __4: 1998,
    __5: "GUMENI MEDVJEDIĆI",
    __6: "X",
  },
  {
    "": 87,
    __1: "",
    __2: 10,
    __3: "MATIJA",
    "BJELOVAR POWERLIFTING": "DIMINIĆ",
    __4: 1996,
    __5: "OSIJEK 031",
    __6: "X",
  },
  {
    "": 88,
    __1: "",
    __2: 11,
    __3: "MATEJ",
    "BJELOVAR POWERLIFTING": "BELAK",
    __4: 1999,
    __5: "OSIJEK 031",
    __6: "X",
  },
  {
    "": 89,
    __1: "",
    __2: 12,
    __3: "TOMISLAV",
    "BJELOVAR POWERLIFTING": "PREMERL",
    __4: 2001,
    __5: "ŠTANGA",
    __6: "X",
  },
  {
    "": 90,
    __1: "",
    __2: 13,
    __3: "JOSIP",
    "BJELOVAR POWERLIFTING": "DUJMOVIĆ",
    __4: 1997,
    __5: "TAZ",
    __6: "X",
  },
  {
    "": "",
    __1: 120,
    __2: "",
    __3: "",
    "BJELOVAR POWERLIFTING": "",
    __4: "",
    __5: "",
    __6: "",
  },
  {
    "": 91,
    __1: "",
    __2: 1,
    __3: "KARLO",
    "BJELOVAR POWERLIFTING": "MIKEŠIĆ",
    __4: 2000,
    __5: "REBEL WARRIOR",
    __6: 835,
  },
  {
    "": 92,
    __1: "",
    __2: 2,
    __3: "LUKA",
    "BJELOVAR POWERLIFTING": "GREŽINA",
    __4: 2005,
    __5: "ŠTANGA",
    __6: 683,
  },
  {
    "": 93,
    __1: "",
    __2: 3,
    __3: "SEBASTIJAN",
    "BJELOVAR POWERLIFTING": "ŠPOLJARIĆ",
    __4: 2000,
    __5: "NABILDANI MOZAK",
    __6: 645,
  },
  {
    "": 94,
    __1: "",
    __2: 4,
    __3: "LOVRO",
    "BJELOVAR POWERLIFTING": "LELEKOVIĆ",
    __4: 1998,
    __5: "TAZ",
    __6: 560,
  },
  {
    "": 95,
    __1: "",
    __2: 5,
    __3: "IVAN",
    "BJELOVAR POWERLIFTING": "ŽUGAJ",
    __4: 1999,
    __5: "GUMENI MEDVJEDIĆI",
    __6: "X",
  },
  {
    "": "",
    __1: "120+",
    __2: "",
    __3: "",
    "BJELOVAR POWERLIFTING": "",
    __4: "",
    __5: "",
    __6: "",
  },
  {
    "": 96,
    __1: "",
    __2: 1,
    __3: "ALEKSANDAR",
    "BJELOVAR POWERLIFTING": "NOVAK",
    __4: 1997,
    __5: "BJELOWBAR",
    __6: 600,
  },
  {
    "": 97,
    __1: "",
    __2: 2,
    __3: "ILIJA",
    "BJELOVAR POWERLIFTING": "PETROVIĆ",
    __4: 1999,
    __5: "OSIJEK 031",
    __6: "X",
  },
  {
    "": 98,
    __1: "",
    __2: 3,
    __3: "PETAR",
    "BJELOVAR POWERLIFTING": "RAJKOVIĆ",
    __4: 1998,
    __5: "SPIRITUS FORTIS",
    __6: "X",
  },
  {
    "": 99,
    __1: "",
    __2: 4,
    __3: "MATIJA",
    "BJELOVAR POWERLIFTING": "OŽEG",
    __4: 1995,
    __5: "BJELOWBAR",
    __6: "X",
  },
  {
    "": "",
    __1: "120+ EQ",
    __2: "",
    __3: "",
    "BJELOVAR POWERLIFTING": "",
    __4: "",
    __5: "",
    __6: "",
  },
  {
    "": 100,
    __1: "",
    __2: 1,
    __3: "ANTONIO",
    "BJELOVAR POWERLIFTING": "POŠKOVIĆ CHIOUREAS",
    __4: 1991,
    __5: "POWER CREW",
    __6: "X",
  },
  {
    "": "",
    __1: "MASTER I",
    __2: "",
    __3: "",
    "BJELOVAR POWERLIFTING": "",
    __4: "",
    __5: "",
    __6: "",
  },
  {
    "": "",
    __1: 93,
    __2: "",
    __3: "",
    "BJELOVAR POWERLIFTING": "",
    __4: "",
    __5: "",
    __6: "",
  },
  {
    "": 101,
    __1: "",
    __2: 1,
    __3: "ADIS",
    "BJELOVAR POWERLIFTING": "JAKIĆ",
    __4: 1983,
    __5: "GUMENI MEDVJEDIĆI",
    __6: "X",
  },
  {
    "": 102,
    __1: "",
    __2: 2,
    __3: "DARIO",
    "BJELOVAR POWERLIFTING": "ČIČAK",
    __4: 1984,
    __5: "TAZ",
    __6: "X",
  },
  {
    "": 103,
    __1: "",
    __2: 3,
    __3: "MATE",
    "BJELOVAR POWERLIFTING": "MALEŠ",
    __4: 1984,
    __5: "REBEL WARRIOR",
    __6: "X",
  },
  {
    "": "",
    __1: 105,
    __2: "",
    __3: "",
    "BJELOVAR POWERLIFTING": "",
    __4: "",
    __5: "",
    __6: "",
  },
  {
    "": 104,
    __1: "",
    __2: 1,
    __3: "NIKOLA",
    "BJELOVAR POWERLIFTING": "DAJKOVIĆ",
    __4: 1975,
    __5: "TAZ",
    __6: 571,
  },
  {
    "": 105,
    __1: "",
    __2: 2,
    __3: "IVAN",
    "BJELOVAR POWERLIFTING": "ĆORIĆ",
    __4: 1983,
    __5: "SAMO MIŠIĆI",
    __6: "X",
  },
  {
    "": "",
    __1: 120,
    __2: "",
    __3: "",
    "BJELOVAR POWERLIFTING": "",
    __4: "",
    __5: "",
    __6: "",
  },
  {
    "": 106,
    __1: "",
    __2: 1,
    __3: "KREŠO",
    "BJELOVAR POWERLIFTING": "SAMARĐIJA",
    __4: 1977,
    __5: "BELIŠĆE",
    __6: "X",
  },
  {
    "": "",
    __1: "120+",
    __2: "",
    __3: "",
    "BJELOVAR POWERLIFTING": "",
    __4: "",
    __5: "",
    __6: "",
  },
  {
    "": 107,
    __1: "",
    __2: 1,
    __3: "ROBERT",
    "BJELOVAR POWERLIFTING": "BLEŠĆ",
    __4: 1978,
    __5: "POZOJ",
    __6: 655,
  },
  {
    "": "",
    __1: "MASTER II",
    __2: "",
    __3: "",
    "BJELOVAR POWERLIFTING": "",
    __4: "",
    __5: "",
    __6: "",
  },
  {
    "": "",
    __1: "",
    __2: "",
    __3: "",
    "BJELOVAR POWERLIFTING": "",
    __4: "",
    __5: "",
    __6: "",
  },
  {
    "": 108,
    __1: "",
    __2: 1,
    __3: "DEJAN",
    "BJELOVAR POWERLIFTING": "RODIGER",
    __4: 1974,
    __5: "POZOJ",
    __6: "X",
  },
];

export const benchOnly2024 = [
  {
    "": "",
    "BJELOVAR BENCH PRESS": "ŽENE",
    __1: "",
    __2: "",
    __3: "",
    __4: "",
    __5: "",
    __6: "",
    __7: "",
    __8: "",
  },
  {
    "": "",
    "BJELOVAR BENCH PRESS": "SUB-JUNIOR",
    __1: "",
    __2: "",
    __3: "",
    __4: "",
    __5: "",
    __6: "",
    __7: "",
    __8: "",
  },
  {
    "": "",
    "BJELOVAR BENCH PRESS": 52,
    __1: "",
    __2: "",
    __3: "",
    __4: "",
    __5: "",
    __6: "",
    __7: "",
    __8: "",
  },
  {
    "": 1,
    "BJELOVAR BENCH PRESS": "",
    __1: 1,
    __2: "ANAMARIJA",
    __3: "MAMIĆ",
    __4: 2009,
    __5: "REBEL WARRIOR",
    __6: 60,
    __7: "",
    __8: "",
  },
  {
    "": "",
    "BJELOVAR BENCH PRESS": 84,
    __1: "",
    __2: "",
    __3: "",
    __4: "",
    __5: "",
    __6: "",
    __7: "",
    __8: "",
  },
  {
    "": 2,
    "BJELOVAR BENCH PRESS": "",
    __1: 1,
    __2: "TIHANA",
    __3: "MAJETIĆ",
    __4: 2006,
    __5: "VIROVITICA",
    __6: "X",
    __7: "",
    __8: "",
  },
  {
    "": "",
    "BJELOVAR BENCH PRESS": "JUNIOR",
    __1: "",
    __2: "",
    __3: "",
    __4: "",
    __5: "",
    __6: "",
    __7: "",
    __8: "",
  },
  {
    "": "",
    "BJELOVAR BENCH PRESS": 57,
    __1: "",
    __2: "",
    __3: "",
    __4: "",
    __5: "",
    __6: "",
    __7: "",
    __8: "",
  },
  {
    "": 3,
    "BJELOVAR BENCH PRESS": "",
    __1: 1,
    __2: "MELISA",
    __3: "MATULIN",
    __4: 2005,
    __5: "POZOJ",
    __6: 82.5,
    __7: "",
    __8: "",
  },
  {
    "": "",
    "BJELOVAR BENCH PRESS": 63,
    __1: "",
    __2: "",
    __3: "",
    __4: "",
    __5: "",
    __6: "",
    __7: "",
    __8: "",
  },
  {
    "": 4,
    "BJELOVAR BENCH PRESS": "",
    __1: 1,
    __2: "LEONORA",
    __3: "KUQI",
    __4: "2004.",
    __5: "POZOJ",
    __6: 40,
    __7: "",
    __8: "",
  },
  {
    "": 5,
    "BJELOVAR BENCH PRESS": "",
    __1: 2,
    __2: "PETRA",
    __3: "ČOVO",
    __4: "2005.",
    __5: "REBEL WARRIOR",
    __6: "X",
    __7: "",
    __8: "",
  },
  {
    "": "",
    "BJELOVAR BENCH PRESS": "OPEN",
    __1: "",
    __2: "",
    __3: "",
    __4: "",
    __5: "",
    __6: "",
    __7: "",
    __8: "",
  },
  {
    "": "",
    "BJELOVAR BENCH PRESS": 52,
    __1: "",
    __2: "",
    __3: "",
    __4: "",
    __5: "",
    __6: "",
    __7: "",
    __8: "",
  },
  {
    "": 6,
    "BJELOVAR BENCH PRESS": "",
    __1: 1,
    __2: "SINDY",
    __3: "BUBEK",
    __4: 1998,
    __5: "POZOJ",
    __6: 84,
    __7: "",
    __8: "",
  },
  {
    "": "",
    "BJELOVAR BENCH PRESS": "",
    __1: "",
    __2: "",
    __3: "",
    __4: "",
    __5: "",
    __6: "",
    __7: "",
    __8: "",
  },
  {
    "": 7,
    "BJELOVAR BENCH PRESS": "",
    __1: 1,
    __2: "ENIA",
    __3: "MAJETIĆ",
    __4: 1996,
    __5: "VIROVITICA",
    __6: 52.5,
    __7: "",
    __8: "",
  },
  {
    "": "",
    "BJELOVAR BENCH PRESS": 69,
    __1: "",
    __2: "",
    __3: "",
    __4: "",
    __5: "",
    __6: "",
    __7: "",
    __8: "",
  },
  {
    "": 8,
    "BJELOVAR BENCH PRESS": "",
    __1: 1,
    __2: "MATEA",
    __3: "BUMBA",
    __4: 1999,
    __5: "VIROVITICA",
    __6: 90,
    __7: "",
    __8: "",
  },
  {
    "": "",
    "BJELOVAR BENCH PRESS": "MUŠKI",
    __1: "",
    __2: "",
    __3: "",
    __4: "",
    __5: "",
    __6: "",
    __7: "",
    __8: "",
  },
  {
    "": "",
    "BJELOVAR BENCH PRESS": "SUB-JUNIOR",
    __1: "",
    __2: "",
    __3: "",
    __4: "",
    __5: "",
    __6: "",
    __7: "",
    __8: "",
  },
  {
    "": "",
    "BJELOVAR BENCH PRESS": 74,
    __1: "",
    __2: "",
    __3: "",
    __4: "",
    __5: "",
    __6: "",
    __7: "",
    __8: "",
  },
  {
    "": 1,
    "BJELOVAR BENCH PRESS": "",
    __1: 1,
    __2: "DAVID",
    __3: "ŠLEŽAK",
    __4: 2006,
    __5: "POZOJ",
    __6: 108,
    __7: "",
    __8: "",
  },
  {
    "": 2,
    "BJELOVAR BENCH PRESS": "",
    __1: 2,
    __2: "ANTE",
    __3: "BAKOVIĆ",
    __4: 2006,
    __5: "REBEL WARRIOR",
    __6: "X",
    __7: "",
    __8: "",
  },
  {
    "": "",
    "BJELOVAR BENCH PRESS": 93,
    __1: "",
    __2: "",
    __3: "",
    __4: "",
    __5: "",
    __6: "",
    __7: "",
    __8: "",
  },
  {
    "": 3,
    "BJELOVAR BENCH PRESS": "",
    __1: 1,
    __2: "NIKOLA",
    __3: "ZGREBEC",
    __4: 2006,
    __5: "POZOJ",
    __6: 145,
    __7: "",
    __8: "",
  },
  {
    "": 4,
    "BJELOVAR BENCH PRESS": "",
    __1: 2,
    __2: "MIHAEL",
    __3: "BOGDAN",
    __4: 2009,
    __5: "ULTIMATE",
    __6: "X",
    __7: "",
    __8: "",
  },
  {
    "": "",
    "BJELOVAR BENCH PRESS": "MUŠKI",
    __1: "",
    __2: "",
    __3: "",
    __4: "",
    __5: "",
    __6: "",
    __7: "",
    __8: "",
  },
  {
    "": "",
    "BJELOVAR BENCH PRESS": "JUNIOR",
    __1: "",
    __2: "",
    __3: "",
    __4: "",
    __5: "",
    __6: "",
    __7: "",
    __8: "",
  },
  {
    "": "",
    "BJELOVAR BENCH PRESS": 93,
    __1: "",
    __2: "",
    __3: "",
    __4: "",
    __5: "",
    __6: "",
    __7: "",
    __8: "",
  },
  {
    "": 5,
    "BJELOVAR BENCH PRESS": "",
    __1: 1,
    __2: "MATIJA",
    __3: "VRANIĆ",
    __4: 2005,
    __5: "ŠTANGA",
    __6: 145,
    __7: "",
    __8: "",
  },
  {
    "": 6,
    "BJELOVAR BENCH PRESS": "",
    __1: 2,
    __2: "DINO",
    __3: "RADINOVIĆ",
    __4: 2003,
    __5: "REBEL WARRIOR",
    __6: 142.5,
    __7: "",
    __8: "",
  },
  {
    "": 7,
    "BJELOVAR BENCH PRESS": "",
    __1: 3,
    __2: "LEON",
    __3: "ĐURKIN",
    __4: 2004,
    __5: "POZOJ",
    __6: 112.5,
    __7: "",
    __8: "",
  },
  {
    "": "",
    "BJELOVAR BENCH PRESS": "OPEN",
    __1: "",
    __2: "",
    __3: "",
    __4: "",
    __5: "",
    __6: "",
    __7: "",
    __8: "",
  },
  {
    "": "",
    "BJELOVAR BENCH PRESS": 66,
    __1: "",
    __2: "",
    __3: "",
    __4: "",
    __5: "",
    __6: "",
    __7: "",
    __8: "",
  },
  {
    "": 8,
    "BJELOVAR BENCH PRESS": "",
    __1: 1,
    __2: "KARLO",
    __3: "BIBIĆ",
    __4: 1994,
    __5: "KRATOS",
    __6: "X",
    __7: "",
    __8: "",
  },
  {
    "": "",
    "BJELOVAR BENCH PRESS": "",
    __1: "",
    __2: "",
    __3: "",
    __4: "",
    __5: "",
    __6: "",
    __7: "",
    __8: "",
  },
  {
    "": "",
    "BJELOVAR BENCH PRESS": 74,
    __1: "",
    __2: "",
    __3: "",
    __4: "",
    __5: "",
    __6: "",
    __7: "",
    __8: "",
  },
  {
    "": 9,
    "BJELOVAR BENCH PRESS": "",
    __1: 1,
    __2: "ANTONIO",
    __3: "MILETIĆ",
    __4: 1995,
    __5: "VIROVITICA",
    __6: 85,
    __7: "",
    __8: "",
  },
  {
    "": "",
    "BJELOVAR BENCH PRESS": 83,
    __1: "",
    __2: "",
    __3: "",
    __4: "",
    __5: "",
    __6: "",
    __7: "",
    __8: "",
  },
  {
    "": 10,
    "BJELOVAR BENCH PRESS": "",
    __1: 1,
    __2: "LEON",
    __3: "ROZMAN",
    __4: 1996,
    __5: "NABILDANI MOZAK",
    __6: 130,
    __7: "",
    __8: "",
  },
  {
    "": 11,
    "BJELOVAR BENCH PRESS": "",
    __1: 2,
    __2: "NIKOLA",
    __3: "PUH",
    __4: 1999,
    __5: "POZOJ",
    __6: "X",
    __7: "",
    __8: "",
  },
  {
    "": "",
    "BJELOVAR BENCH PRESS": 93,
    __1: "",
    __2: "",
    __3: "",
    __4: "",
    __5: "",
    __6: "",
    __7: "",
    __8: "",
  },
  {
    "": 12,
    "BJELOVAR BENCH PRESS": "",
    __1: 1,
    __2: "WILLIAM",
    __3: "VIČEVIĆ",
    __4: 1992,
    __5: "TAZ",
    __6: 170,
    __7: "",
    __8: "",
  },
  {
    "": 13,
    "BJELOVAR BENCH PRESS": "",
    __1: 2,
    __2: "MIHAEL",
    __3: "BALLER",
    __4: 1998,
    __5: "NABILDANI MOZAK",
    __6: 147.5,
    __7: "",
    __8: "",
  },
  {
    "": 14,
    "BJELOVAR BENCH PRESS": "",
    __1: 3,
    __2: "SVEN",
    __3: "ŠĆEKIĆ",
    __4: 2000,
    __5: "NABILDANI MOZAK",
    __6: 122.5,
    __7: "",
    __8: "",
  },
  {
    "": 15,
    "BJELOVAR BENCH PRESS": "",
    __1: 4,
    __2: "MARIO",
    __3: "PARAŽDIK",
    __4: 2000,
    __5: "NABILDANI MOZAK",
    __6: 122.5,
    __7: "",
    __8: "",
  },
  {
    "": "",
    "BJELOVAR BENCH PRESS": 105,
    __1: "",
    __2: "",
    __3: "",
    __4: "",
    __5: "",
    __6: "",
    __7: "",
    __8: "",
  },
  {
    "": 16,
    "BJELOVAR BENCH PRESS": "",
    __1: 1,
    __2: "GORAN",
    __3: "ŠIMIĆ",
    __4: 1990,
    __5: "ŠIBENIK",
    __6: 185,
    __7: "",
    __8: "",
  },
  {
    "": "",
    "BJELOVAR BENCH PRESS": 120,
    __1: "",
    __2: "",
    __3: "",
    __4: "",
    __5: "",
    __6: "",
    __7: "",
    __8: "",
  },
  {
    "": 17,
    "BJELOVAR BENCH PRESS": "",
    __1: 1,
    __2: "JOSIP",
    __3: "TORIĆ",
    __4: 1997,
    __5: "NABILDANI MOZAK",
    __6: 185,
    __7: "",
    __8: "",
  },
  {
    "": 18,
    "BJELOVAR BENCH PRESS": "",
    __1: 2,
    __2: "JOSIP",
    __3: "JURETA",
    __4: 1998,
    __5: "REBEL WARRIOR",
    __6: 180,
    __7: "",
    __8: "",
  },
  {
    "": 19,
    "BJELOVAR BENCH PRESS": "",
    __1: 3,
    __2: "MARIO",
    __3: "LESJAK",
    __4: 1981,
    __5: "ULTIMATE",
    __6: "X",
    __7: "",
    __8: "",
  },
  {
    "": "",
    "BJELOVAR BENCH PRESS": "MASTER I",
    __1: "",
    __2: "",
    __3: "",
    __4: "",
    __5: "",
    __6: "",
    __7: "",
    __8: "",
  },
  {
    "": "",
    "BJELOVAR BENCH PRESS": 93,
    __1: "",
    __2: "",
    __3: "",
    __4: "",
    __5: "",
    __6: "",
    __7: "",
    __8: "",
  },
  {
    "": 20,
    "BJELOVAR BENCH PRESS": "",
    __1: 1,
    __2: "MATE",
    __3: "MALEŠ",
    __4: 1984,
    __5: "REBEL WARRIOR",
    __6: 137.5,
    __7: "",
    __8: "",
  },
  {
    "": "",
    "BJELOVAR BENCH PRESS": 120,
    __1: "",
    __2: "",
    __3: "",
    __4: "",
    __5: "",
    __6: "",
    __7: "",
    __8: "",
  },
  {
    "": 21,
    "BJELOVAR BENCH PRESS": "",
    __1: 1,
    __2: "IVICA",
    __3: "ĆEPIĆ",
    __4: 1976,
    __5: "SAMO MIŠIĆI",
    __6: 155,
    __7: "",
    __8: "",
  },
  {
    "": "",
    "BJELOVAR BENCH PRESS": "MASTER II",
    __1: "",
    __2: "",
    __3: "",
    __4: "",
    __5: "",
    __6: "",
    __7: "",
    __8: "",
  },
  {
    "": "",
    "BJELOVAR BENCH PRESS": 93,
    __1: "",
    __2: "",
    __3: "",
    __4: "",
    __5: "",
    __6: "",
    __7: "",
    __8: "",
  },
  {
    "": 22,
    "BJELOVAR BENCH PRESS": "",
    __1: 1,
    __2: "IVAN",
    __3: "OVČAR",
    __4: 1966,
    __5: "POZOJ",
    __6: 127.5,
    __7: "",
    __8: "",
  },
];
